### PR TITLE
BitbucketClient: prevent NPE when comment is deleted

### LINKED ISSUE #67: NullPointerException when fetching pull request with deleted comments
### Expected Behavior

SonarQube Scanner in Jenkins (using this plugin) should update Bitbucket pull request comments with new scan statuses. 

### Actual Behavior

Received `NullPointerException` with stack trace:

```scala
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$isFromUs$1(BitbucketClient.scala:145)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:150)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:150)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:150)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:149)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:312)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestCommentsPage$1(BitbucketClient.scala:148)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:172)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:171)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:319)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.findOwnPullRequestComments(BitbucketClient.scala:171)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.ch$mibex$bitbucket$sonar$review$SonarReviewPostJob$$handlePullRequest(SonarReviewPostJob.scala:41)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:27)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:25)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.execute(SonarReviewPostJob.scala:25)
	at org.sonar.scanner.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:66)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:84)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

### Plug-in version, SonarQube version, CI system, build type

* Plugin version: 1.2.1
* SonarQube version: 6.5 (build 27846)
* CI system: Jenkins, version: 2.89.1
* Build type: Jenkins Pipeline, JavaScript build

The NPE is coming from this line: https://github.com/mibexsoftware/sonar-bitbucket-plugin/blob/v1.2.1/src/main/scala/ch/mibex/bitbucket/sonar/client/BitbucketClient.scala#L145

and when I tested the Bitbucket API endpoint it (`fetchPage`) is using (`https://api.bitbucket.org/2.0/repositories/{account}/{repoSlug}/pullrequests/{prId}/comments`), I noticed that deleted comments are returned with a `user` value of `null`, e.g.:

```json
{
    "pagelen": 10,
    "size": 51,
    "values": [
        {
            "links": <snip>,
            "deleted": true,
            "pullrequest": <snip>,
            "content": {
                "raw": "",
                "markup": "markdown",
                "html": ""
            },
            "created_on": "2017-11-24T11:38:30.264053+00:00",
            "user": null,
            "inline": {
                "to": 376,
                "from": null,
                "path": "fake.js"
            },
            "updated_on": "2017-11-29T14:56:42.214876+00:00",
            "type": "pullrequest_comment",
            "id": 50383913
        },
    ]
}
```

I assume this bit then fails because `user` is `null`, and therefore cannot have a property `uuid`:

```scala
comment("user").asInstanceOf[Map[String, Any]]("uuid").asInstanceOf[String] equals uuid
```

It sounds like something has changed in the Bitbucket REST API but I wasn't able to find any changelogs etc. describing such a change. This has been working fine so far, started happening today.

### PR DESCRIPTION
**Pull request by mikkopiu**
Fixes #67 

Attempt at fixing a possible `NullPointerException` when a comment has `"user": null`, when calling `fetchPage`. This occurs when a comment has been deleted.

I'm not familiar with Scala, so not sure if this is the idiomatic way to do this.

Tested as working on same setup as described in issue #67

### CODE REVIEW

**Comment by mikkopiu** [comment]
I'd like to add test cases for this but couldn't figure out a proper way to test this as its inside another method which in turn loads data from an API.

**Comment by rhaex** [comment]
I tested a compiled version of the master branch with this fix in our Sonar server, and it still triggers an NPE.

>Caused by: java.lang.NullPointerException
at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$isFromUs$1(BitbucketClient.scala:148)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:153)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:153)
at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
at scala.collection.immutable.List.foreach(List.scala:381)
at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:153)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:152)
at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:315)
at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestCommentsPage$1(BitbucketClient.scala:151)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:175)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:174)
at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:322)
at ch.mibex.bitbucket.sonar.client.BitbucketClient.findOwnPullRequestComments(BitbucketClient.scala:174)
at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.ch$mibex$bitbucket$sonar$review$SonarReviewPostJob$$handlePullRequest(SonarReviewPostJob.scala:43)
at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:29)
at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:27)
at scala.collection.immutable.List.foreach(List.scala:381)
at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.execute(SonarReviewPostJob.scala:27)
at org.sonar.scanner.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58)
at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:66)
at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:94)
at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
at com.sun.proxy.$Proxy23.execute(Unknown Source)
at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:77)
... 23 more

**Comment by mikkopiu** [comment]
Weird, seemed to work in our SonarQube, I'll test again tomorrow.

**Comment by nfalco79** [comment]
I'm trying and seems not fix the issue (at least on our PRs)

> Caused by: java.lang.NullPointerException
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$isFromUs$1(BitbucketClient.scala:148)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:153)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:153)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:153)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:152)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:315)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestCommentsPage$1(BitbucketClient.scala:151)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:175)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:174)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:322)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.findOwnPullRequestComments(BitbucketClient.scala:174)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.ch$mibex$bitbucket$sonar$review$SonarReviewPostJob$$handlePullRequest(SonarReviewPostJob.scala:43)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:29)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:27)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.execute(SonarReviewPostJob.scala:27)
	at org.sonar.batch.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:87)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy23.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:78)
	... 23 more

I think the problem is that in case of null getOrElse returns a map { "uuid": null } where later you perform `null.asInstanceOf[String] equals uuid`

**Comment by nfalco79** [comment]
I confirm that `Option(comment("user").asInstanceOf[Map[String, Any]]).getOrElse(Map("uuid" -> ""))("uuid").asInstanceOf[String] equals uuid` works in my case

**Comment by NicoTexas** [comment]
This is the stack trace I get just now with version 1.2.1
`Caused by: java.lang.NullPointerException
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$isFromUs$1(BitbucketClient.scala:145)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:150)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3$$anonfun$apply$2.apply(BitbucketClient.scala:150)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:150)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$3.apply(BitbucketClient.scala:149)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:312)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestCommentsPage$1(BitbucketClient.scala:148)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:172)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$findOwnPullRequestComments$1.apply(BitbucketClient.scala:171)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.forEachResultPage(BitbucketClient.scala:319)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.findOwnPullRequestComments(BitbucketClient.scala:171)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.ch$mibex$bitbucket$sonar$review$SonarReviewPostJob$$handlePullRequest(SonarReviewPostJob.scala:41)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:27)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob$$anonfun$execute$1.apply(SonarReviewPostJob.scala:25)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ch.mibex.bitbucket.sonar.review.SonarReviewPostJob.execute(SonarReviewPostJob.scala:25)
	at org.sonar.scanner.postjob.PostJobWrapper.executeOn(PostJobWrapper.java:58)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:66)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:84)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy51.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:77)`

**Comment by mikkopiu** [comment]
@rhaex: which branch did you compile, my fork or this repo's master? And did you delete the old plugin & restart SonarQube? Only asking because my compiled `.jar` still seems to be working fine.

Tested like so:

1. Checkout my fork (this PR)
2. Built with `mvn clean install`
3. Copied `.jar` over to `${SONAR_HOME}/extensions/plugins/` and deleted old version of plugin
4. Restarted SonarQube
5. Created PR in Bitbucket, and added a single comment
6. Deleted the comment
7. Ran build in Jenkins
8. SonarQube successfully added the appropriate comments and didn't throw the NPE

**Comment by rhaex** [comment]
Repo's master with the fix from your PR applied, the solution a few comments earlier seems to work:

`Option(comment("user").asInstanceOf[Map[String, Any]]).getOrElse(Map("uuid" -> ""))("uuid").asInstanceOf[String] equals uuid`, where the small difference is that you returned null in the getOrElse, and this returns empty String.

But what I did exactly:
- Check out master
- Apply the change from your PR
- Maven package
- Stop SonarQube
- Delete the old plugin jar, and replace it with the newly compiled jar
- Restarted SonarQube
- Ran Bamboo build that crashes because it links to a pull request where we I removed one of the plugins comments

Did you create and delete your own comment? Because that seems to be working fine, it throws an NPE when you have it create issue comments on a PR, and then remove one of the plugins comments, and rerun the build. I think that may be the small difference.

**Comment by mikkopiu** [comment]
Oh, right, didn't catch that difference. And yes, I added my own comments and deleted it, but I've now also tested this by running the Jenkins job 3 times (using this PR's fix, not the String-version):

1. SonarQube adds initial comment
2. SQ deletes initial comment and adds 2nd comment
3. SQ *successfully* deletes 2nd comment and add 3rd comment
    - Previously, it would fail in this step, as `"user" == null`

And on the `null` vs `""`, shouldn't `null.asInstanceOf[String]` cast `null` to `"null"` effectively? Meaning that both versions should work equally? Or could that be dependent on the Java version?

We are running:

```
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by mrueegg** [comment]
Looks good to me, thanks for your contribution!

**Comment by nfalco79** [comment]
@mikkopiu 
> And on the null vs "", shouldn't null.asInstanceOf[String] cast null to "null" effectively? 

No cast are performed null -> "null". I compile with oracle java 1.8 build 101. With code of this PR I got NPE on row 148 (stackstrace on my previous comment) instead 145.

**Comment by mikkopiu** [comment]
Switched to the empty String version, wonder why the original version works on my instance...

**Comment by Jtag84** [comment]
This fixed the issue for me with the last commit. 

Thanks

**Comment by andrew-makarenko** [comment]
Any news on this? When it can be merged?

**Comment by mrueegg** [comment]
Merged. Thank you @mikkopiu for contributing this fix and all other participants for reviewing and  testing it!

**Comment by kmalmur** [comment]
the issue is still present in 1.2.2. Stacktrace added here: https://github.com/mibexsoftware/sonar-bitbucket-plugin/issues/67

**Pull request merged**
